In [1]:
import pandas as pd
import datetime

In [ ]:
file2_name = "daily_trading_info_2019-2020.xlsx"
file2 = pd.read_excel(file2_name, sheet_name = None)
company_index = []
company_index = list(file2.keys())[:]

In [ ]:
from talib import abstract

In [ ]:
pd.read_excel(company_index[0]+".xlsx")

In [ ]:
df = pd.read_excel(company_index[0]+".xlsx")

In [ ]:
df

In [ ]:
import talib as tb

In [ ]:
inputs = {
    'open': df["open"],
    'high': df["high"],
    'low':  df["low"],
    'close': df["close"],
    'volume': df["volume"]
}
# uses close prices (default)

out1 = abstract.SMA(inputs, timeperiod=7)
out2 = abstract.SMA(inputs, timeperiod=20)
out3 = abstract.SMA(inputs, timeperiod=30)
out4 = abstract.SMA(inputs, timeperiod=60)
out5 = abstract.SMA(inputs, timeperiod=120)
out6 = tb.ADXR(df["high"], df["low"], df["close"], timeperiod=14)
out7 = tb.AROON(df["high"], df["low"],  timeperiod=14)
out8 = tb.AROONOSC(df["high"], df["low"],  timeperiod=14)
out9 = tb.BOP(df["open"], df["high"], df["low"], df["close"])
out10 = tb.CCI(df["high"], df["low"], df["close"], timeperiod=14)
out11 = tb.DX(df["high"], df["low"], df["close"], timeperiod=14)
out12 = tb.MFI(df["high"], df["low"], df["close"], df["volume"], timeperiod=14)
out13 = tb.MINUS_DI(df["high"], df["low"], df["close"], timeperiod=14)
out14 = tb.MINUS_DM(df["high"], df["low"], timeperiod=14) 
out15 = tb.PPO(df["close"], fastperiod=12, slowperiod=26, matype=0) 
out16 = tb.ROCP(df["close"], timeperiod=10) 
out17 = tb.ROCR(df["close"], timeperiod=10) 
out18 = tb.ROCR100(df["close"], timeperiod=10) 
out19 = abstract.RSI(inputs, timeperiod=30)
out20 = abstract.RSI(inputs, timeperiod=60)
out21 = abstract.MOM(inputs, timeperiod=20)
out22 = abstract.MOM(inputs, timeperiod=30)
out23 = tb.NATR(df["high"], df["low"], df["close"], timeperiod=28)
out24 = tb.NATR(df["high"], df["low"], df["close"], timeperiod=42)
out25 = tb.ADX(df["high"], df["low"], df["close"], timeperiod=28)
out26 = tb.ADX(df["high"], df["low"], df["close"], timeperiod=42)
out27 = tb.CMO(df["close"], timeperiod=30)
out28 = tb.CMO(df["close"], timeperiod=60)
out29 = tb.DEMA(df["close"], timeperiod=60)
out30 = tb.DEMA(df["close"], timeperiod=90)
out31 = tb.KAMA(df["close"], timeperiod=15)
out32 = tb.KAMA(df["close"], timeperiod=30)
out33 = tb.KAMA(df["close"], timeperiod=60)

In [ ]:
out19
out20
out21

In [ ]:
pd.DataFrame(out32, columns=["kama30"]).head(20)

In [ ]:
out5

In [ ]:
out6

In [ ]:
out7

In [ ]:
out9

In [ ]:
out1
out2
out3
out4
out5
out6
out7
out8
out9
out10
out11
out12
out13
out14
out15
out16
out17
out18
out19
out20
out21
out22
out23
out24
out25
out26
out27
out28
out29
out30
out31
out32
out33

In [ ]:
pd.concat([df, pd.DataFrame(out1, columns=["ma7"])\
          , pd.DataFrame(out2, columns=["ma20"]), pd.DataFrame(out3, columns=["ma30"]),pd.DataFrame(out4, columns=["ma60"]),pd.DataFrame(out5, columns=["ma120"]),pd.DataFrame(out6, columns=["adxr"]),pd.DataFrame(out7, columns=["aroon"]),pd.DataFrame(out8, columns=["aroonosc"]),pd.DataFrame(out9, columns=["bop"]),pd.DataFrame(out10, columns=["cci"]),pd.DataFrame(out11, columns=["dx"]),pd.DataFrame(out12, columns=["mfi"]),pd.DataFrame(out13, columns=["minus_di"]),pd.DataFrame(out14, columns=["minus_dm"]),pd.DataFrame(out15, columns=["ppo"]),pd.DataFrame(out16, columns=["rocp"]),pd.DataFrame(out17, columns=["rocr"]),pd.DataFrame(out18, columns=["rocr100"]),pd.DataFrame(out19, columns=["rsi30"]),pd.DataFrame(out20, columns=["rsi60"]),pd.DataFrame(out21, columns=["mom20"]),pd.DataFrame(out22, columns=["mom30"]),pd.DataFrame(out23, columns=["natr28"]),pd.DataFrame(out24, columns=["natr42"]),pd.DataFrame(out25, columns=["natr42"]),pd.DataFrame(out25, columns=["adx28"]),pd.DataFrame(out26, columns=["adx42"]),pd.DataFrame(out27, columns=["cmo30"]),pd.DataFrame(out28, columns=["cmo60"]),pd.DataFrame(out29, columns=["dema60"]),pd.DataFrame(out30, columns=["dema90"]),pd.DataFrame(out31, columns=["kama15"]),pd.DataFrame(out32, columns=["kama30"]),pd.DataFrame(out33, columns=["kama60"])], axis=1).head(30)

In [ ]:
for w in range(0, len(company_index)):
# for w in range(0, 3):
    df = pd.read_excel(company_index[w]+".xlsx")
    inputs = {
    'open': df["open"],
    'high': df["high"],
    'low':  df["low"],
    'close': df["close"],
    'volume': df["volume"]
    }
    # uses close prices (default)
   
    
    out1 = abstract.SMA(inputs, timeperiod=7)
    out2 = abstract.SMA(inputs, timeperiod=20)
    out3 = abstract.SMA(inputs, timeperiod=30)
    out4 = abstract.SMA(inputs, timeperiod=60)
    out5 = abstract.SMA(inputs, timeperiod=120)
    out6 = tb.ADXR(df["high"], df["low"], df["close"], timeperiod=14)
    out7 = tb.AROON(df["high"], df["low"],  timeperiod=14)
    out8 = tb.AROONOSC(df["high"], df["low"],  timeperiod=14)
    out9 = tb.BOP(df["open"], df["high"], df["low"], df["close"])
    out10 = tb.CCI(df["high"], df["low"], df["close"], timeperiod=14)
    out11 = tb.DX(df["high"], df["low"], df["close"], timeperiod=14)
    out12 = tb.MFI(df["high"], df["low"], df["close"], df["volume"], timeperiod=14)
    out13 = tb.MINUS_DI(df["high"], df["low"], df["close"], timeperiod=14)
    out14 = tb.MINUS_DM(df["high"], df["low"], timeperiod=14) 
    out15 = tb.PPO(df["close"], fastperiod=12, slowperiod=26, matype=0) 
    out16 = tb.ROCP(df["close"], timeperiod=10) 
    out17 = tb.ROCR(df["close"], timeperiod=10) 
    out18 = tb.ROCR100(df["close"], timeperiod=10) 
    out19 = abstract.RSI(inputs, timeperiod=30)
    out20 = abstract.RSI(inputs, timeperiod=60)
    out21 = abstract.MOM(inputs, timeperiod=20)
    out22 = abstract.MOM(inputs, timeperiod=30)
    out23 = tb.NATR(df["high"], df["low"], df["close"], timeperiod=28)
    out24 = tb.NATR(df["high"], df["low"], df["close"], timeperiod=42)
    out25 = tb.ADX(df["high"], df["low"], df["close"], timeperiod=28)
    out26 = tb.ADX(df["high"], df["low"], df["close"], timeperiod=42)
    out27 = tb.CMO(df["close"], timeperiod=30)
    out28 = tb.CMO(df["close"], timeperiod=60)
    out29 = tb.DEMA(df["close"], timeperiod=60)
    out30 = tb.DEMA(df["close"], timeperiod=90)
    out31 = tb.KAMA(df["close"], timeperiod=15)
    out32 = tb.KAMA(df["close"], timeperiod=30)
    out33 = tb.KAMA(df["close"], timeperiod=60)
   
    a = pd.DataFrame(out1, columns=["ma7"])
    b = pd.DataFrame(out2, columns=["ma20"])
    c = pd.DataFrame(out3, columns=["ma30"])
    d = pd.DataFrame(out4, columns=["ma60"])
    e = pd.DataFrame(out5, columns=["ma120"])
    f = pd.DataFrame(out6, columns=["adxr"])
    g = pd.DataFrame(out7, columns=["aroon"])
    h = pd.DataFrame(out8, columns=["aroonosc"])
    i = pd.DataFrame(out9, columns=["bop"])
    j = pd.DataFrame(out10, columns=["cci"])
    k = pd.DataFrame(out11, columns=["dx"])
    l = pd.DataFrame(out12, columns=["mfi"])
    m = pd.DataFrame(out13, columns=["minus_di"])
    n = pd.DataFrame(out14, columns=["minus_dm"])
    o = pd.DataFrame(out15, columns=["ppo"])
    p = pd.DataFrame(out16, columns=["rocp"])
    q = pd.DataFrame(out17, columns=["rocr"])
    r = pd.DataFrame(out18, columns=["rocr100"])
    x = pd.DataFrame(out19, columns=["rsi30"])
    t = pd.DataFrame(out20, columns=["rsi60"])
    u = pd.DataFrame(out21, columns=["mom20"])
    v = pd.DataFrame(out22, columns=["mom30"])
    w1 = pd.DataFrame(out23, columns=["natr28"])
    x = pd.DataFrame(out24, columns=["natr42"])
    y = pd.DataFrame(out25, columns=["adx28"])
    z = pd.DataFrame(out26, columns=["adx42"])
    aa = pd.DataFrame(out27, columns=["cmo30"])
    ab = pd.DataFrame(out28, columns=["cmo60"])
    ac = pd.DataFrame(out29, columns=["dema60"])
    ad = pd.DataFrame(out30, columns=["dema90"])
    ae = pd.DataFrame(out31, columns=["kama15"])
    af = pd.DataFrame(out32, columns=["kama30"])
    ag = pd.DataFrame(out33, columns=["kama60"])
    
    pd.concat([df,a , b, c, d, e, f, g, h, i, j, k, l, m, n,\
o, p, q, r, x, t, u, v, w1, x, y, z , aa, ab, ac, ad, ae, af,ag], \
axis=1).to_excel(company_index[w]+".xlsx", sheet_name = company_index[w], index=False)
    if(w%100==0):
        print(w)

In [ ]:
company_index[w]

In [ ]:
train_set = pd.read_excel("strategy_results_train.xlsx")

In [ ]:
#aa = pd.DataFrame(out27, columns=["cmo30"])
    ab = pd.DataFrame(out28, columns=["cmo60"])
    ac = pd.DataFrame(out29, columns=["dema60"])
    ad = pd.DataFrame(out30, columns=["dema90"])
    ae = pd.DataFrame(out31, columns=["kama15"])
    af = pd.DataFrame(out32, columns=["kama30"])
    ag = pd.DataFrame(out33, columns=["kama60"])
    , aa, ab, ac, ad, ae, af,ag

In [ ]:
import copy

In [ ]:
dataset = copy.deepcopy(train_set)

In [ ]:
temp = []
for i in range(0, dataset.shape[0]):
# for i in range(0, 10):
    if(i%1000==0):
        print(i, datetime.datetime.now())
    trade_company = dataset.iloc[i][0].split("_")[0]
    trade_date    = dataset.iloc[i][0].split("_")[1]
    df = pd.read_excel(trade_company+".xlsx")
    trade_date_datetime = datetime.date(int(trade_date[:4]), int(trade_date[4:]), 1) - datetime.timedelta(days=1)
    lower_index = 0
    for index in range(0, df.shape[0]):
        if(df["date"].iloc[index]< trade_date_datetime):
            lower_index = index
        else:
            break
#     print(list(df.iloc[lower_index, :]))
    temp.append(list(df.iloc[lower_index, :]))

In [ ]:
temp[1]

In [ ]:
pd.DataFrame(temp).to_excel("train_output.xlsx", index=False)

In [ ]:
testset = pd.read_excel("sampleSubmission.xlsx")

In [ ]:
testset.head()

In [ ]:
temp = []
for i in range(0, testset.shape[0]):
# for i in range(0, 10):
    if(i%1000==0):
        print(i, datetime.datetime.now())
    trade_company = testset.iloc[i][0].split("_")[0]
    trade_date    = testset.iloc[i][0].split("_")[1]
    df = pd.read_excel(trade_company+".xlsx")
    trade_date_datetime = datetime.date(int(trade_date[:4]), int(trade_date[4:]), 1) - datetime.timedelta(days=1)
    lower_index = 0
    for index in range(0, df.shape[0]):
        if(df["date"].iloc[index]< trade_date_datetime):
            lower_index = index
        else:
            break
#     print(list(df.iloc[lower_index, :]))
    if(lower_index==0):
        temp.append(dash = ["-","","","","","","","",""])
    else:
        temp.append(list(df.iloc[lower_index, :]))

In [ ]:
pd.DataFrame(temp).to_excel("test_output.xlsx", index=False)

In [ ]:
temp[0]

In [ ]:
dash = ["-","","","","","","","",""]

In [ ]:
import pandas as pd

In [2]:
data = pd.read_excel("strategy_results_train17.xlsx")

In [3]:
data.head()

,id,label,0,1,2,3,4,5,6,7,...,61,62,63,64,65,66,67,68,69,70
0,SHSE.600085_201501,0,2014-12-30,20.900000,22.090000,20.799999,22.049999,25457468.0,21.291999,21.369,...,20.962527,21.617908,21.227352,20.374825,21.217142,21.6650,21.083000,19.993667,19.337583,36.146447
1,SHSE.600085_201502,1,2015-01-30,22.990000,23.190001,22.510000,22.580000,7880595.0,23.320000,23.386,...,22.965852,23.235488,22.843367,22.373391,23.415715,23.5860,22.873667,21.590667,20.246750,28.338702
2,SHSE.600085_201503,1,2015-02-27,22.520000,22.670000,22.400000,22.540001,9263796.0,22.442000,22.106,...,22.962907,22.637368,22.744453,22.324221,22.232857,22.4540,22.877667,22.351000,20.628000,24.160934
3,SHSE.600085_201504,1,2015-03-30,26.219999,26.440001,25.820000,26.230000,16125626.0,26.378000,25.148,...,24.206943,24.942466,24.076600,23.185191,25.780000,24.0025,23.378333,23.219167,21.545667,25.427469
4,SHSE.600085_201505,1,2015-04-29,32.580002,33.639999,32.279999,33.180000,13959795.0,32.888000,32.902,...,29.499756,32.352646,32.207153,29.244995,32.982857,31.2410,29.301333,25.910667,23.639833,47.916521

In [4]:
data2 = pd.concat( [data.iloc[:, 1], data.iloc[:, 8:]], axis=1)

In [5]:
data2.head()

,label,6,7,8,9,10,11,12,13,14,...,61,62,63,64,65,66,67,68,69,70
0,0,21.291999,21.369,21.636000,0.142243,21.789657,21.428042,61.764303,0.230000,0.721951,...,20.962527,21.617908,21.227352,20.374825,21.217142,21.6650,21.083000,19.993667,19.337583,36.146447
1,1,23.320000,23.386,23.590000,0.417949,23.863963,23.194083,46.331140,-1.850000,0.120449,...,22.965852,23.235488,22.843367,22.373391,23.415715,23.5860,22.873667,21.590667,20.246750,28.338702
2,1,22.442000,22.106,22.165333,-0.577756,22.585287,22.782792,50.955797,-0.070000,1.178770,...,22.962907,22.637368,22.744453,22.324221,22.232857,22.4540,22.877667,22.351000,20.628000,24.160934
3,1,26.378000,25.148,24.380667,1.174423,25.069993,23.111667,69.989214,2.559999,-0.037316,...,24.206943,24.942466,24.076600,23.185191,25.780000,24.0025,23.378333,23.219167,21.545667,25.427469
4,1,32.888000,32.902,32.436000,2.774423,33.247219,29.494500,65.947116,1.500000,0.283715,...,29.499756,32.352646,32.207153,29.244995,32.982857,31.2410,29.301333,25.910667,23.639833,47.916521

In [6]:
data2.isnull().any()

label    False
6         True
7         True
8         True
9         True
10        True
11        True
12        True
13        True
14        True
15        True
16        True
17        True
18        True
19        True
20        True
21        True
22        True
32        True
33        True
34        True
35        True
36        True
37        True
56        True
57        True
58        True
59        True
60        True
61        True
62        True
63        True
64        True
65        True
66        True
67        True
68        True
69        True
70        True
dtype: bool

In [7]:
data2 = data2.dropna(axis = 0)
data2.isnull().any()

label    False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
32       False
33       False
34       False
35       False
36       False
37       False
56       False
57       False
58       False
59       False
60       False
61       False
62       False
63       False
64       False
65       False
66       False
67       False
68       False
69       False
70       False
dtype: bool

In [8]:
y = data2["label"]
y

0     0
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     0
9     0
10    1
11    1
12    0
13    0
14    1
15    0
16    1
17    1
18    1
19    0
20    1
21    1
22    0
23    0
24    0
25    0
26    1
27    0
28    0
29    1
30    0
31    0
32    1
33    1
34    1
35    1
36    1
37    0
38    1
39    1
40    1
41    0
42    1
43    0
44    1
45    0
46    1
47    0
Name: label, dtype: int64

In [35]:
X = data2.iloc[:, 1:-6]

In [37]:
X

,6,7,8,9,10,11,12,13,14,15,...,37,56,57,58,59,60,61,62,63,64
0,21.291999,21.369000,21.636000,0.142243,21.789657,21.428042,61.764303,0.230000,0.721951,1.176761e+07,...,36.146447,24.497506,18.878973,21.149106,16.372813,21.375288,20.962527,21.617908,21.227352,20.374825
1,23.320000,23.386000,23.590000,0.417949,23.863963,23.194083,46.331140,-1.850000,0.120449,-1.618153e+06,...,28.338702,25.264784,21.688250,5.890647,9.690370,23.538223,22.965852,23.235488,22.843367,22.373391
2,22.442000,22.106000,22.165333,-0.577756,22.585287,22.782792,50.955797,-0.070000,1.178770,4.056584e+06,...,24.160934,20.842150,17.826829,4.910934,7.687995,23.082298,22.962907,22.637368,22.744453,22.324221
3,26.378000,25.148000,24.380667,1.174423,25.069993,23.111667,69.989214,2.559999,-0.037316,3.198869e+07,...,25.427469,18.021693,15.075386,27.998624,21.254970,24.518435,24.206943,24.942466,24.076600,23.185191
4,32.888000,32.902000,32.436000,2.774423,33.247219,29.494500,65.947116,1.500000,0.283715,7.305273e+06,...,47.916521,32.947272,24.830342,33.428815,29.847241,31.032531,29.499756,32.352646,32.207153,29.244995
5,37.378001,34.734000,33.891333,1.227500,35.774880,32.148583,69.598066,7.280001,-0.008150,2.251591e+07,...,33.059982,30.081798,25.783514,33.462817,29.761351,34.572353,33.202627,34.954654,32.841404,32.909647
6,37.439999,38.791999,39.765333,-0.257821,40.243346,40.234208,35.712303,-9.379997,1.359660,-9.858892e+06,...,39.655617,33.217197,29.753064,-7.533831,3.514725,40.263165,38.867764,39.594097,38.599041,38.947433
7,29.240000,29.739000,29.284667,-0.337820,28.757291,29.367166,47.009405,1.219999,1.299653,7.937620e+06,...,29.513367,22.006768,20.446930,-5.576159,-1.155917,32.098216,33.759034,30.468584,32.886725,36.939695
8,23.559999,26.362000,27.796000,-1.662756,25.952497,29.738208,40.897662,-5.500000,1.164988,-1.052797e+07,...,17.838879,16.817672,15.396562,-13.039959,-6.983986,28.536951,30.716420,27.204973,31.008812,33.825370
9,23.284000,23.422000,23.625333,-0.462500,22.474512,24.203250,37.109877,-0.300001,0.546458,1.316733e+06,...,27.418821,19.949989,16.180325,-17.340286,-10.200254,24.030622,26.378121,25.098056,26.580713,29.158059
10,26.274000,25.993000,25.780000,1.177179,25.125107,24.480833,51.305700,-0.360001,0.513199,6.510661e+06,...,23.601262,14.010769,12.668209,-3.042541,-3.521879,24.328815,25.499623,25.666573,26.059016,28.500168
11,26.608000,26.785000,26.861333,0.201795,26.736597,26.513792,43.516181,-0.680000,1.290514,3.909623e+05,...,25.152291,11.971810,9.321325,-5.055612,-3.639630,25.616908,25.816396,26.261440,26.448581,28.016107
12,39.578000,39.498000,37.769333,4.581987,39.210696,32.968916,71.475975,7.020000,0.315633,8.609886e+06,...,46.300452,30.520044,18.736271,35.105016,21.297655,34.956490,32.649068,38.746112,37.367667,35.902446
13,28.922000,30.009000,30.686000,-3.531987,31.432303,34.731625,41.870948,-2.809999,1.003288,2.510832e+06,...,32.840583,21.496880,16.772618,-7.379114,-2.268226,33.271759,32.817238,32.989855,36.415150,35.862605
14,29.894000,30.629000,30.144666,0.337436,29.900632,29.997791,40.380562,-2.170000,-0.205124,-5.073347e+06,...,21.154833,14.984419,13.352300,-8.780753,-3.252912,31.576100,31.852673,32.179372,33.618567,35.216749
15,29.262000,29.175000,28.752666,0.385385,28.536259,28.520208,58.510380,2.080000,0.544340,8.088628e+06,...,15.694289,9.382809,9.058315,3.399282,1.348937,29.229022,29.940514,29.813965,31.992247,33.153084
16,27.884000,28.243000,28.801333,-0.642179,28.331361,29.475292,38.661003,-1.959999,0.150160,-3.029717e+06,...,15.455029,8.534282,7.420194,-10.285881,-4.395750,28.712701,29.284875,28.614011,31.382218,32.086890
17,26.918000,27.101000,27.326000,-0.452372,26.970595,27.827125,35.738270,-1.130001,1.898512,6.740147e+05,...,15.884131,7.484195,5.740710,-15.098404,-6.865449,27.411225,28.028733,27.831171,28.906873,30.934949
18,28.312000,27.744000,27.563333,0.177500,27.626720,27.295250,64.325621,2.449999,0.137052,1.363408e+07,...,15.046511,7.177400,5.029383,11.769180,2.977349,27.281007,27.547834,27.930582,28.525258,30.225207
19,31.564000,31.434000,31.852000,0.667628,31.940376,30.990750,61.367228,-0.600000,-0.666997,1.774416e+06,...,38.283863,22.111818,13.143924,17.459771,8.455728,30.685968,29.987513,31.490131,31.004674,30.695889
20,30.910000,31.355000,31.340667,0.281731,31.544559,31.158375,48.164492,-0.930000,1.363363,-7.552173e+06,...,25.779371,23.039388,16.330341,3.076786,3.235904,31.400260,30.903729,31.162444,31.015807,30.954781
21,30.648000,30.721000,30.790667,-0.257115,30.862889,30.987792,45.886924,0.279999,-0.487116,-4.578961e+04,...,14.840154,17.033376,15.251802,-1.313703,1.265058,31.211747,31.058360,30.968352,30.970593,30.953504
22,31.816000,31.413000,31.313333,0.282115,31.431066,30.922667,56.177023,0.789999,0.532150,1.458217e+06,...,13.439212,15.945052,15.059428,8.002572,5.237331,31.471864,31.355476,31.286210,31.035311,30.984484
23,34.025999,33.123000,32.594666,0.684807,33.173102,31.788833,70.873212,2.879999,-0.203996,5.243217e+06,...,22.839106,20.420468,17.402237,28.701518,16.358458,32.611512,32.308436,32.819625,32.236454,31.514089
24,31.120000,31.279000,31.329333,-0.955705,31.530822,32.327250,45.824537,0.019999,0.688449,1.306762e+06,...,19.498414,13.967306,14.986689,-3.823132,0.241149,32.108602,32.235532,31.755650,32.587703,31.830178
25,30.360000,30.190000,30.355333,-0.562564,30.225944,30.872458,43.371427,0.660000,0.236371,3.291672e+06,...,16.222630,11.438513,11.141127,-9.870041,-3.730539,30.931588,31.370581,30.867660,30.980900,31.609449
26,30.798000,30.641000,30.552667,0.204936,30.413423,30.367083,48.127742,-0.130001,1.106480,5.502083e+06,...,17.585955,8.720701,8.350442,-5.596874,-2.537278,30.583411,30.950450,30.705288,30.820710,31.367074
27,31.980000,32.077000,31.873333,0.607051,31.887101,31.234917,47.397675,-0.200001,0.823802,9.522631e+05,...,20.548007,12.531870,9.654434,0.614634,1.045861,31.415075,31.386462,31.779727,31.559509,31.291552
28,31.516000,31.802000,31.587333,-0.072692,31.756826,31.691333,42.866293,-0.090000,0.779015,5.882549e+06,...,17.356763,9.771658,8.101951,-5.068147,-1.474768,31.627101,31.575170,31.709317,31.628786,31.434071
29,32.132000,31.790000,31.504667,0.134103,31.719383,31.320042,57.132378,1.080002,0.064807,1.169538e+07,...,15.431587,8.551530,6.686015,8.133474,4.673876,31.610154,31.578464,31.696849,31.536143,31.457464
30,35.078000,34.200000,33.921333,0.776026,34.346551,32.910042,62.306499,1.639999,0.895374,2.210870e+06,...,28.802402,18.010261,11.916644,20.778283,14.595069,33.505329,33.035762,33.474967,33.125459,32.205274
31,32.864001,32.851001,33.125334,-0.775705,33.356928,33.891083,44.050550,-1.230000,0.999992,2.188519e+06,...,25.624803,14.281347,11.651502,-2.146374,1.900183,33.643729,33.484113,33.148898,33.388728,32.624840
32,32.162001,32.362001,32.386667,-0.044679,32.255187,32.452042,45.156180,-0.090000,0.957211,-1.484685e+06,...,19.520362,10.270339,7.881683,-5.431331,-1.021680,32.743994,32.951423,32.765925,32.728168,32.590938
33,32.050000,31.759000,31.688000,-0.131282,31.673684,31.837542,59.152171,0.809999,-0.078140,8.689498e+05,...,24.382931,12.164172,8.088195,3.258933,1.285295,31.954729,32.280935,31.946508,32.307203,32.181671
34,34.066000,33.777000,33.420667,0.858205,33.560360,32.503000,68.576072,1.510002,-0.498418,5.600471e+06,...,35.170858,18.661943,11.219963,22.783346,12.327470,32.991031,32.925233,33.561685,33.007608,32.410490
35,33.216000,34.013000,34.036000,-0.033141,34.073668,34.103833,37.959800,-1.329998,0.239366,5.592212e+06,...,34.389578,20.912212,14.726543,-9.459545,-3.047037,33.914088,33.731647,33.798500,33.742112,33.017433
36,32.152000,32.249000,32.332000,-0.300385,32.257446,32.687292,44.108684,0.070004,0.694348,4.105371e+06,...,20.119898,12.540845,9.559327,-7.628807,-3.265853,32.775580,33.001541,32.794822,33.132665,32.939438
37,34.348000,34.283000,33.917333,0.715577,34.016391,33.185625,52.894572,0.410000,0.182304,5.362101e+05,...,24.786128,15.118973,11.077112,5.974155,4.540416,33.630245,33.546205,33.772718,33.465893,33.051907
38,32.636000,32.444000,32.734667,-0.864615,32.804216,33.529083,47.570370,0.049999,0.740218,4.962320e+06,...,26.463020,14.304935,10.149733,-3.158823,-1.054469,33.062850,33.189412,32.897539,33.393069,32.949069
39,34.076000,33.996000,33.760667,0.555705,33.817178,33.181167,62.108485,1.160000,0.602846,9.095031e+06,...,18.720123,10.236049,7.975837,14.120434,8.238310,33.525375,33.466841,33.425584,33.457664,33.115053
40,34.244001,35.087001,35.810001,0.205192,35.506209,35.531250,53.526181,-1.259998,0.278683,1.213476e+06,...,20.492733,13.594103,10.431503,8.069081,7.087255,35.180300,34.830640,35.618764,35.380686,34.115902
41,40.556000,40.505000,40.106667,2.335769,40.613820,37.932459,52.489525,-1.500000,0.325517,-3.930301e+06,...,36.629670,27.928956,19.905222,12.153588,12.458864,39.206881,38.130026,39.995122,37.994307,37.523447
42,35.743999,36.407000,36.938000,-1.479679,37.076152,38.528667,38.042572,-2.360001,0.528169,-4.025960e+06,...,26.919913,20.045292,17.961848,-9.865782,-2.290602,38.248942,38.186229,37.368461,37.680864,37.704931
43,34.542000,35.072000,35.262666,0.121474,34.681119,35.235333,35.595489,-2.669998,3.263638,1.972370e+05,...,23.567086,14.384200,12.140792,-15.233544,-6.680363,35.908020,36.571799,35.493000,35.961454,37.260660
44,31.744001,30.963000,31.202000,-0.891346,30.676858,31.912417,44.014725,0.250000,1.069858,3.805357e+05,...,40.631887,24.278635,16.035139,-14.484959,-9.797488,31.870542,33.155796,31.481262,32.639516,33.410007
45,31.234000,30.579000,30.376000,-0.412500,30.151279,30.709042,57.668870,2.370001,-0.200357,2.094512e+06,...,35.732750,27.377054,19.089004,-2.918068,-5.584825,30.272131,31.247335,30.879129,31.634951,31.822465
46,28.924000,28.946000,29.100000,-0.845385,28.687313,29.959375,40.052884,0.020000,1.193306,-2.778400e+05,...,29.048970,27.606701,20.896712,-17.087019,-13.367339,28.839648,29.648547,30.154720,30.677802,30.552455
47,29.246000,29.673000,29.682000,0.288269,29.287293,29.487000,43.360218,-1.080000,0.607991,-7.522165e+05,...,18.982031,22.457970,20.120310,-9.945988,-9.219038,28.763825,28.967569,30.034342,30.430953,30.254974

In [38]:

X = X.dropna(axis = 0)

In [39]:
X.isnull().any()

6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
32    False
33    False
34    False
35    False
36    False
37    False
56    False
57    False
58    False
59    False
60    False
61    False
62    False
63    False
64    False
dtype: bool

In [40]:
X.shape

(48, 32)

In [41]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
clf = GradientBoostingClassifier()
clf.fit(X, y)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [42]:
testdata = pd.read_excel("sampleSubmission17.xlsx")

In [43]:
testdata = testdata.fillna(0)
testdata.isnull().any()

id        False
label     False
ma5       False
ma10      False
ma15      False
apo       False
dema      False
trima     False
rsi       False
mom       False
beta      False
adosc     False
natr      False
trange    False
adx       False
cmo       False
willr     False
roc       False
ultosc    False
32        False
33        False
34        False
35        False
36        False
37        False
56        False
57        False
58        False
59        False
60        False
61        False
62        False
63        False
64        False
65        False
66        False
67        False
68        False
69        False
70        False
dtype: bool

In [44]:
testdata.iloc[:, 2:-6]

,ma5,ma10,ma15,apo,dema,trima,rsi,mom,beta,adosc,...,37,56,57,58,59,60,61,62,63,64
0,27.258000,27.573000,28.198000,-0.695641,27.718808,29.033417,40.796678,-2.510000,1.002494,2.535317e+06,...,21.978933,23.699999,21.176055,-14.710835,-11.805518,27.843283,28.001731,28.703206,29.406270,29.665012
1,26.624000,26.698000,26.724667,-0.084295,26.330274,26.802416,40.945731,-0.500000,-0.230494,-2.921724e+05,...,28.848266,25.740335,23.147367,-15.925412,-13.092381,26.386671,26.566882,27.468550,27.630198,28.708857
2,28.890000,28.863000,28.408667,1.086282,28.363972,27.376833,60.789262,0.549999,0.426938,3.296768e+06,...,26.886327,19.612946,18.661476,9.294140,-0.194607,27.409341,27.057094,28.599205,28.070446,28.587239
3,29.532000,30.037000,30.157333,0.141795,30.249325,30.035625,52.700566,-0.389999,0.471348,-2.671194e+06,...,31.858004,20.156416,15.585038,7.000400,2.008233,29.440186,28.643181,29.723495,29.760442,28.909795
4,31.514000,32.125000,32.192000,0.716218,32.229146,31.395583,47.196492,-0.570002,1.338949,-6.654858e+06,...,31.620454,24.695027,17.780914,4.409116,3.656420,31.550067,30.557351,31.319914,30.834172,30.688380
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11358,86.210001,86.955000,86.357333,3.460192,87.527481,82.818916,50.174304,-4.000000,1.568918,-2.164396e+04,...,33.145078,28.762586,24.861340,11.485292,14.283546,86.231590,84.656134,83.728554,80.770839,80.185304
11359,77.136000,80.214001,82.662001,-2.762948,82.222467,85.846625,34.462281,-10.879997,0.260138,-1.612410e+06,...,27.005928,22.686444,21.071539,-11.590915,0.351109,85.761814,86.360855,80.704429,81.994700,82.699481
11360,70.966000,71.855001,72.971334,-1.730512,71.528337,75.037126,41.540826,-2.870003,0.705415,-1.383875e+06,...,36.249789,22.497318,17.314303,-13.354875,-3.896398,76.588067,79.902748,74.313234,74.058558,80.846313
11361,82.976001,79.619000,77.530667,3.766923,78.106197,73.651959,64.605778,6.629997,0.940703,3.920510e+06,...,32.029075,18.728728,14.623439,14.561953,9.430624,77.489275,79.459884,80.517762,76.040753,79.329351
11362,81.462000,82.899000,84.118667,-0.380321,83.968712,84.258542,48.329598,-3.130005,0.656567,-4.726638e+05,...,30.801281,19.697898,15.668266,3.045815,4.812876,82.727055,83.061425,84.243167,82.366182,79.877922

In [45]:
result = clf.predict(testdata.iloc[:, 2:-6])

In [46]:
pd.DataFrame(result).to_excel("prediction.xlsx", index=False)

In [ ]:
#4

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_excel("strategy_results_train6.xlsx")

In [ ]:
data.head()

In [ ]:
data2 = pd.concat( [data.iloc[:, 1], data.iloc[:, 8:]], axis=1)

In [ ]:
data2.head()

In [ ]:
data2.isnull().any()

In [ ]:
data2 = data2.dropna(axis = 0)
data2.isnull().any()

In [ ]:
y = data2["label"]
y

In [ ]:
X = data2.iloc[:, 1:]

In [ ]:
X

In [ ]:
X = X.dropna(axis = 0)

In [ ]:
X.isnull().any()

In [ ]:
from sklearn.preprocessing import Normalizer

transformer = Normalizer().fit(X)  # fit does nothing.

X = transformer.transform(X)

In [ ]:
X.shape

In [ ]:
# from sklearn.aensemble import RandomForestClassifier
# clf = RandomForestClassifier()
# clf.fit(X, y)

In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, VotingClassifier, AdaBoostClassifier, GradientBoostingClassifier
clf1 = LogisticRegression()
clf2 = RandomForestClassifier()
clf3 = AdaBoostClassifier()
clf4 = GradientBoostingClassifier()
clf5 = SVC()
clf = VotingClassifier(estimators=[
        ('lr', clf1), ('rf', clf2), ('ada', clf3), ('gra', clf4), ('svc', clf5)], voting='hard')
clf.fit(X, y)

In [ ]:
y

In [ ]:
testdata = pd.read_excel("sampleSubmission6.xlsx")

In [ ]:
testdata = testdata.fillna(0)
testdata.isnull().any()

In [ ]:
testdata.iloc[:, 2:]

In [ ]:
transformer.transform(testdata.iloc[:, 2:])

In [ ]:
result = clf.predict(transformer.transform(testdata.iloc[:, 2:]))

In [ ]:
pd.DataFrame(result).to_excel("prediction.xlsx", index=False)